export const FETCH_WILDLIFE_DATA = "FETCH_WILDLIFE_DATA";
export const FETCH_PROGRAM_DATA = "FETCH_PROGRAM_DATA";
export const FETCH_BLOG_DATA = "FETCH_BLOG_DATA";
export const FETCH_GOV_PROGRAM_DATA = "FETCH_GOV_PROGRAM_DATA";